/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipotrabalho;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Scanner;

/**
 *
 * @author acaro
 */
public class InterfaceJukebox extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public InterfaceJukebox() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Abas = new javax.swing.JTabbedPane();
        abaConversao = new javax.swing.JPanel();
        TextoDigite = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CaixaTexto = new javax.swing.JTextArea();
        bConverter = new javax.swing.JButton();
        TextoConfiguracoes = new javax.swing.JLabel();
        TextoInstrumento = new javax.swing.JLabel();
        TextoBpm = new javax.swing.JLabel();
        selInstrumento = new javax.swing.JComboBox<>();
        selBpm = new javax.swing.JComboBox<>();
        TextoDownload = new javax.swing.JLabel();
        bDownload = new javax.swing.JButton();
        bSelecionar = new javax.swing.JButton();
        TextoSelecione = new javax.swing.JLabel();
        CaixaNome = new javax.swing.JTextField();
        TextoNome = new javax.swing.JLabel();
        TextoMid = new javax.swing.JLabel();
        abaHelp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabMapeamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEXTO MUSICAL ♪ - Converte seu texto em uma música!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Abas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        abaConversao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TextoDigite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextoDigite.setText("Digite aqui o texto a ser convertido:");

        CaixaTexto.setColumns(20);
        CaixaTexto.setRows(5);
        CaixaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(CaixaTexto);

        bConverter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bConverter.setText("Converter");
        bConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConverterActionPerformed(evt);
            }
        });

        TextoConfiguracoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextoConfiguracoes.setText("Configurações iniciais:");

        TextoInstrumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextoInstrumento.setText("Instrumento");

        TextoBpm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextoBpm.setText("BPM");

        selInstrumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selInstrumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piano", "Violão", "Guitarra", "Violino" }));

        selBpm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selBpm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40", "70", "100", "130", "160", "190", "220", "250", "280", "310" }));

        TextoDownload.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextoDownload.setText("Faça o download da sua música:");

        bDownload.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bDownload.setText("Download");

        bSelecionar.setText("Selecionar");
        bSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelecionarActionPerformed(evt);
            }
        });

        TextoSelecione.setText("Selecione o arquivo a ser convertido:");

        TextoNome.setText("Nome do arquivo:");

        TextoMid.setText(".MID");

        javax.swing.GroupLayout abaConversaoLayout = new javax.swing.GroupLayout(abaConversao);
        abaConversao.setLayout(abaConversaoLayout);
        abaConversaoLayout.setHorizontalGroup(
            abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaConversaoLayout.createSequentialGroup()
                .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaConversaoLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(bSelecionar)
                        .addGap(53, 367, Short.MAX_VALUE))
                    .addGroup(abaConversaoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaConversaoLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoInstrumento)
                                    .addGroup(abaConversaoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TextoBpm)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaConversaoLayout.createSequentialGroup()
                                        .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selBpm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(92, 92, 92)
                                        .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextoDigite)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(abaConversaoLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(abaConversaoLayout.createSequentialGroup()
                                                .addGap(207, 207, 207)
                                                .addComponent(bConverter))
                                            .addGroup(abaConversaoLayout.createSequentialGroup()
                                                .addComponent(TextoNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CaixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TextoMid)
                                                .addGap(18, 18, 18)
                                                .addComponent(bDownload))))))
                            .addComponent(TextoSelecione)
                            .addComponent(TextoConfiguracoes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(abaConversaoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(TextoDownload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaConversaoLayout.setVerticalGroup(
            abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaConversaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoConfiguracoes)
                    .addComponent(TextoDigite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaConversaoLayout.createSequentialGroup()
                        .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoInstrumento)
                            .addComponent(selInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoBpm)
                            .addComponent(selBpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(TextoSelecione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConverter)
                    .addComponent(bSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(TextoDownload)
                .addGap(26, 26, 26)
                .addGroup(abaConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDownload)
                    .addComponent(CaixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoNome)
                    .addComponent(TextoMid))
                .addGap(26, 26, 26))
        );

        Abas.addTab("Conversão", abaConversao);

        tabMapeamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A", "Nota Lá"},
                {"B", "Nota Si"},
                {"C", "Nota Dó"},
                {"D", "Nota Ré"},
                {"E", "Nota Mi"},
                {"F", "Nota Fá"},
                {"G", "Nota Sol"},
                {"a, b, c, d, e, f, g", "Se caractere anterior era NOTA(A até G), repete nota; Caso contrário, silêncio(pausa)"},
                {"Espaço", "Aumenta volume para o DOBRO do volume; Se não puder aumentar, voltar ao voluma padrão"},
                {"!", "Trocar instrumento para o instrumento 114 (Agogo)"},
                {"O, o, I, i, U, u (vogais)", "Trocar instrumento para o instrumento 7 (Harpsichord)"},
                {"Consoante (tirando notas)", "Se caractere anterior era NOTA(A até G), repete nota; Caso contrário, silêncio(pausa)"},
                {"Número", "Trocar instrumento para o instrumento cujo número é igual ao valor do instrumento ATUAL + valor do dígito"},
                {"?", "Aumenta UMA oitava; Se não puder aumentar volta à oitava defalt (de início)"},
                {"\n (quebra de linha)", "Trocar instrumento para o instrumento 15 (Tubular Bells)"},
                {";", "Trocar instrumento para o instrumento 76 (Pan Flute)"},
                {",", "Trocar instrumento para o instrumento 20 (Church Organ)"},
                {"ELSE", "Se caractere anterior era NOTA(A até G), repete nota; Caso contrário, silêncio(pausa)"},
                {"@", "Nota aleatória"},
                {"+", "Aumenta BPM em 50 unidades (saturar em 310)"},
                {"-", "Diminui BPM em 50 unidades (saturar em 60)"},
                {"#", "Trocar instrumento para o instrumento X (Guitarra)"},
                {"$", "Trocar instrumento para o instrumento 55 (Orquestra)"},
                {"%", "Diminui Uma oitava; Se não puder diminuir, volta à oitava default(de início)"}
            },
            new String [] {
                "Texto", "Ação"
            }
        ));
        tabMapeamento.setShowGrid(true);
        jScrollPane2.setViewportView(tabMapeamento);

        javax.swing.GroupLayout abaHelpLayout = new javax.swing.GroupLayout(abaHelp);
        abaHelp.setLayout(abaHelpLayout);
        abaHelpLayout.setHorizontalGroup(
            abaHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        abaHelpLayout.setVerticalGroup(
            abaHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaHelpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Abas.addTab("Help", abaHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConverterActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_bConverterActionPerformed

        // TODO add your handling code here:
        InterpretadorDeTexto interpretador = new InterpretadorDeTexto();
        interpretador.defineTextoInput(interpretador, CaixaTexto.getText());
        String textoMusical = interpretador.geraTextoParametrizado(interpretador);

        TocadorDeMusica jukebox = new TocadorDeMusica();
        jukebox.defineStaccato(jukebox, textoMusical);
        jukebox.TocaMusica(jukebox);

    }//GEN-LAST:event_bConverterActionPerformed

    private void bSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelecionarActionPerformed
        // TODO add your handling code here:
        //jButton3.addActionListener(new ActionListener() {
            //@Override
            //public void actionPerformed(ActionEvent e)  {
                escolheArquivo txt = new escolheArquivo();
                CaixaTexto.setText(txt.escolhe());

            //}
        //});
    }//GEN-LAST:event_bSelecionarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceJukebox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceJukebox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceJukebox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceJukebox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceJukebox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Abas;
    private javax.swing.JTextField CaixaNome;
    private javax.swing.JTextArea CaixaTexto;
    private javax.swing.JLabel TextoBpm;
    private javax.swing.JLabel TextoConfiguracoes;
    private javax.swing.JLabel TextoDigite;
    private javax.swing.JLabel TextoDownload;
    private javax.swing.JLabel TextoInstrumento;
    private javax.swing.JLabel TextoMid;
    private javax.swing.JLabel TextoNome;
    private javax.swing.JLabel TextoSelecione;
    private javax.swing.JPanel abaConversao;
    private javax.swing.JPanel abaHelp;
    private javax.swing.JButton bConverter;
    private javax.swing.JButton bDownload;
    private javax.swing.JButton bSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> selBpm;
    private javax.swing.JComboBox<String> selInstrumento;
    private javax.swing.JTable tabMapeamento;
    // End of variables declaration//GEN-END:variables
}
